gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft
  assets:
    - "*.png"

  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets


# Site settings
title: Joe M Horvath
description: An Artit's Gallery

# Name of project on Github
baseurl: /

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
